package com.danny.seckill.entity;

import java.util.Date;

public class SeckillRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_record.seckill_item_id
     *
     * @mbggenerated
     */
    private String seckillItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_record.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_record.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_record.id
     *
     * @return the value of seckill_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_record.id
     *
     * @param id the value for seckill_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_record.seckill_item_id
     *
     * @return the value of seckill_record.seckill_item_id
     *
     * @mbggenerated
     */
    public String getSeckillItemId() {
        return seckillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_record.seckill_item_id
     *
     * @param seckillItemId the value for seckill_record.seckill_item_id
     *
     * @mbggenerated
     */
    public void setSeckillItemId(String seckillItemId) {
        this.seckillItemId = seckillItemId == null ? null : seckillItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_record.user_phone
     *
     * @return the value of seckill_record.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_record.user_phone
     *
     * @param userPhone the value for seckill_record.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_record.state
     *
     * @return the value of seckill_record.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_record.state
     *
     * @param state the value for seckill_record.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_record.create_time
     *
     * @return the value of seckill_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_record.create_time
     *
     * @param createTime the value for seckill_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}