package com.danny.seckill.dao;

import com.danny.seckill.entity.SeckillItem;
import com.danny.seckill.entity.SeckillItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int countByExample(SeckillItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int deleteByExample(SeckillItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int insert(SeckillItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int insertSelective(SeckillItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    List<SeckillItem> selectByExample(SeckillItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    SeckillItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SeckillItem record, @Param("example") SeckillItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SeckillItem record, @Param("example") SeckillItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SeckillItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeckillItem record);
}