package com.danny.seckill.dao;

import com.danny.seckill.entity.SeckillRecord;
import com.danny.seckill.entity.SeckillRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int countByExample(SeckillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int deleteByExample(SeckillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int insert(SeckillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int insertSelective(SeckillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    List<SeckillRecord> selectByExample(SeckillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    SeckillRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SeckillRecord record, @Param("example") SeckillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SeckillRecord record, @Param("example") SeckillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SeckillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeckillRecord record);
}